name: Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Code format
      #   run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Vet
        run: go vet ./...
      - name: Unit tests
        run: go test "-coverprofile=coverage.out" ./...
      - name: Function coverage
        run: go tool cover "-func=coverage.out"
      - name: Test build
        run: |
          go build -o winfilezap.exe -ldflags "-X main.version=testbuild" ./cmd/...
          # .\winfilezap.exe
